/**
 * SW Electrical — Cloudflare Pages root Worker
 *
 * Serves the static site and handles the enquiry and EV survey forms
 * end to end. No third-party database. Everything runs in Cloudflare.
 *
 *   POST /api/enquiry     Validate, save to D1, email Sean, respond.
 *   GET  /api/enquiries   Read the enquiry log as JSON. Requires the
 *                         x-admin-secret header. Not linked anywhere.
 *   POST /api/ev-survey    Validate, store photos and video in R2, save
 *                         to D1, email Sean a set of secure view links.
 *   GET  /api/survey-media Serves one stored photo or video, only for
 *                         signed links generated by this worker.
 *
 * ---------------------------------------------------------------------------
 * BINDINGS — Pages > Settings > Bindings > Add
 *   D1 database   Variable name: DB           Database: sw-electrical
 *   R2 bucket     Variable name: SURVEY_PHOTOS  Bucket: sw-electrical-survey-photos
 *
 * VARIABLES — Pages > Settings > Variables and secrets
 *   RESEND_API_KEY   Resend API key                     (Secret)
 *   FROM_EMAIL       website@swelectrical.co.uk         (Text)
 *   TO_EMAIL         info@swelectrical.co.uk            (Text)
 *   ADMIN_SECRET     a long random string you invent    (Secret)
 *                  Also used to sign the survey-media view links, so no
 *                  separate secret is needed for that.
 *   TURNSTILE_SECRET_KEY  Cloudflare Turnstile secret key   (Secret, optional)
 *                  Verifies the Turnstile token from the form. If this
 *                  variable is unset, Turnstile verification is skipped
 *                  entirely — the form keeps working, just without that
 *                  layer, until the key is added.
 *
 * Redeploy after adding bindings or variables.
 * ---------------------------------------------------------------------------
 *
 * ANTI-SPAM — three independent layers, all fail open (a fault in any one
 * never blocks a genuine enquiry from being saved):
 *   1. Honeypot        `company` field, hidden from sighted users. Any bot
 *                       that fills every input trips it.
 *   2. Time-trap        `form_started` timestamp set on page load. A submit
 *                       under MIN_FORM_SECONDS after the page loaded is
 *                       almost certainly scripted, not typed.
 *   3. Rate limit       max RATE_LIMIT_MAX submissions per IP per
 *                       RATE_LIMIT_WINDOW_SECONDS, tracked in the
 *                       form_submissions D1 table.
 *   4. Turnstile        optional, see TURNSTILE_SECRET_KEY above.
 */

const MIN_FORM_SECONDS = 3;
const RATE_LIMIT_MAX = 10;
const RATE_LIMIT_WINDOW_SECONDS = 60 * 60; // 1 hour

/** Returns null if under the limit, or a 429 Response if the IP should be blocked. */
async function checkRateLimit(request, env, endpoint) {
  if (!env.DB) return null; // fail open — a missing binding must never block real enquiries

  const ip = request.headers.get('cf-connecting-ip') || 'unknown';
  const now = Math.floor(Date.now() / 1000);
  const windowStart = now - RATE_LIMIT_WINDOW_SECONDS;

  try {
    const { results } = await env.DB.prepare(
      `SELECT COUNT(*) AS n FROM form_submissions WHERE ip = ? AND endpoint = ? AND created_at > ?`
    ).bind(ip, endpoint, windowStart).all();

    if ((results?.[0]?.n ?? 0) >= RATE_LIMIT_MAX) {
      return json({ error: 'That is a lot of enquiries from this connection in a short time. Please wait a little while, or call Sean directly.' }, 429);
    }

    // Record this attempt even if it later fails validation — failed spam
    // attempts should count towards the limit, not get a free retry.
    await env.DB.prepare(
      `INSERT INTO form_submissions (ip, endpoint, created_at) VALUES (?, ?, ?)`
    ).bind(ip, endpoint, now).run();
  } catch {
    // Table missing or a transient D1 fault — fail open rather than block enquiries.
  }
  return null;
}

/** True if the submission arrived suspiciously fast after the form loaded. */
function failsTimeTrap(formStarted) {
  const started = Number(formStarted);
  if (!started) return false; // no timestamp supplied — don't punish older clients/cached pages
  const elapsed = Date.now() / 1000 - started;
  return elapsed >= 0 && elapsed < MIN_FORM_SECONDS;
}

/** Verifies a Turnstile token. Returns true if Turnstile isn't configured (fail open),
 *  or if the token checks out. Returns false only on a confirmed bad token. */
async function verifyTurnstile(token, env, request) {
  if (!env.TURNSTILE_SECRET_KEY) return true; // not configured yet — no-op until keys are added
  if (!token) return false;

  try {
    const res = await fetch('https://challenges.cloudflare.com/turnstile/v0/siteverify', {
      method: 'POST',
      headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
      body: new URLSearchParams({
        secret: env.TURNSTILE_SECRET_KEY,
        response: token,
        remoteip: request.headers.get('cf-connecting-ip') || ''
      })
    });
    const data = await res.json();
    return !!data.success;
  } catch {
    return true; // Cloudflare's own verify endpoint being down must never block real enquiries
  }
}

export default {
  async fetch(request, env, ctx) {
    const url = new URL(request.url);

    // One canonical host. Requests to www get a permanent redirect to the same
    // path and query on the bare domain, so search engines only ever see one
    // copy of each page and links to the www version pass their value on.
    // Canonical tags already point at the bare domain, but those are a hint;
    // a 301 is an instruction.
    //
    // 308 rather than 301 for non-GET requests: a 301 lets clients turn a POST
    // into a GET on redirect, which would silently drop a form submission.
    if (url.hostname === 'www.swelectrical.co.uk') {
      url.hostname = 'swelectrical.co.uk';
      const status = (request.method === 'GET' || request.method === 'HEAD') ? 301 : 308;
      return Response.redirect(url.toString(), status);
    }

    if (url.pathname === '/api/enquiry') {
      if (request.method !== 'POST') {
        return json({ error: 'POST only' }, 405, { Allow: 'POST' });
      }
      return handleEnquiry(request, env, ctx);
    }

    if (url.pathname === '/api/enquiries') {
      return listEnquiries(request, env);
    }

    if (url.pathname === '/api/ev-survey') {
      if (request.method !== 'POST') {
        return json({ error: 'POST only' }, 405, { Allow: 'POST' });
      }
      return handleEvSurvey(request, env, ctx);
    }

    if (url.pathname === '/api/survey-media') {
      return serveSurveyMedia(request, env);
    }

    return env.ASSETS.fetch(request);
  }
};

/* ------------------------------------------------------------------ */

function json(body, status = 200, extra = {}) {
  return new Response(JSON.stringify(body), {
    status,
    headers: { 'Content-Type': 'application/json', ...extra }
  });
}

// field -> { max length, label shown to the customer }
const FIELDS = {
  name:     { max: 100,  label: 'your name' },
  phone:    { max: 40,   label: 'a phone number' },
  email:    { max: 200,  label: 'an email address' },
  postcode: { max: 12,   label: 'a postcode' },
  service:  { max: 80,   label: 'the service you need', missing: 'Please choose the service you need.' },
  details:  { max: 4000, label: 'a short description of the work' }
};

// Deliberately loose. The job is to catch obvious mistakes (letters typed into
// the phone box, a postcode that is clearly not one) without rejecting valid
// entries: people write numbers with spaces, brackets, +44 prefixes, and a
// customer fumbling their own postcode should still be able to reach Sean.
const PHONE_OK = /^[0-9+()\s.-]{7,}$/;
const UK_POSTCODE_OK = /^[A-Z]{1,2}[0-9][A-Z0-9]?\s*[0-9][A-Z]{2}$/i;
const EMAIL_OK = /^[^@\s]+@[^@\s]+\.[^@\s]+$/;

/** Shared by the enquiry and EV survey forms. Returns null if the contact
 *  details look valid, otherwise { error, field } ready to send as JSON. */
function checkContact(c) {
  if (!EMAIL_OK.test(c.email)) {
    return { error: 'That email address does not look right. Please check it and try again.', field: 'email' };
  }
  if (!PHONE_OK.test(c.phone)) {
    return { error: 'That phone number does not look right. Please use digits only, for example 07700 900123.', field: 'phone' };
  }
  if (!UK_POSTCODE_OK.test(c.postcode)) {
    return { error: 'That postcode does not look right. Please check it, for example SY3 9NT.', field: 'postcode' };
  }
  return null;
}

async function handleEnquiry(request, env, ctx) {
  const limited = await checkRateLimit(request, env, 'enquiry');
  if (limited) return limited;

  let d;
  try {
    d = await request.json();
  } catch {
    return json({ error: 'Your enquiry did not arrive complete. Please try sending it again.' }, 400);
  }

  // Honeypot: bots fill every field, people leave this one alone.
  if (d.company) return json({ ok: true }, 200);

  if (failsTimeTrap(d.form_started)) return json({ ok: true }, 200);

  // Validation messages are written to be read by the customer and to name the
  // field, so a failed submission says what to fix instead of just failing.
  //
  // Field checks run BEFORE Turnstile on purpose. Turnstile tokens are single
  // use: checking it first spent the token on a submission that then failed
  // validation, so the customer's corrected retry was rejected as a failed
  // anti-spam check however right the form now was.
  const clean = {};
  for (const [field, { max, label, missing }] of Object.entries(FIELDS)) {
    const v = String(d[field] ?? '').trim();
    if (!v) return json({ error: missing || `Please enter ${label}.`, field }, 400);
    if (v.length > max) {
      return json({ error: `That ${label.replace(/^(your|an|a|the) /, '')} is too long. Please shorten it and try again.`, field }, 400);
    }
    clean[field] = v;
  }
  const bad = checkContact(clean);
  if (bad) return json(bad, 400);

  if (!(await verifyTurnstile(d['cf-turnstile-response'], env, request))) {
    return json({ error: 'The anti-spam check did not pass. Please tick the box again and resend.', turnstile: true }, 400);
  }

  const preferred = ['Phone', 'WhatsApp', 'Email'].includes(d.preferred) ? d.preferred : null;
  const id = crypto.randomUUID();

  if (!env.DB) return json({ error: 'Something went wrong at our end. Please call or WhatsApp Sean instead.' }, 500);

  try {
    await env.DB.prepare(
      `INSERT INTO enquiries (id, name, phone, email, postcode, service, details, preferred, ip_country)
       VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)`
    )
      .bind(
        id,
        clean.name,
        clean.phone,
        clean.email,
        clean.postcode,
        clean.service,
        clean.details,
        preferred,
        request.headers.get('cf-ipcountry') || null
      )
      .run();
  } catch (err) {
    return json({ error: 'Something went wrong at our end saving your enquiry. Please call or WhatsApp Sean instead.' }, 500);
  }

  // The enquiry is saved. Email is a notification, so send it after the
  // response goes out. A mail failure must never lose the enquiry.
  ctx.waitUntil(sendEmail(env, { id, ...clean, preferred }));

  return json({ ok: true }, 200);
}

async function sendEmail(env, r) {
  if (!env.RESEND_API_KEY || !env.TO_EMAIL || !env.FROM_EMAIL) return;

  const esc = (s) =>
    String(s ?? '').replace(/[<>&]/g, (ch) => ({ '<': '&lt;', '>': '&gt;', '&': '&amp;' }[ch]));

  const rows = [
    ['Name', r.name],
    ['Phone', r.phone],
    ['Email', r.email],
    ['Postcode', r.postcode],
    ['Service', r.service],
    ['Preferred contact', r.preferred || 'Not stated'],
    ['Details', r.details]
  ]
    .map(
      ([k, v]) =>
        `<tr><td style="padding:6px 14px 6px 0;vertical-align:top;color:#4B5B70">${esc(k)}</td>` +
        `<td style="padding:6px 0;vertical-align:top"><strong>${esc(v).replace(/\n/g, '<br>')}</strong></td></tr>`
    )
    .join('');

  const html = `
    <div style="font-family:-apple-system,Segoe UI,sans-serif;color:#011E3E;max-width:600px">
      <h2 style="margin:0 0 4px">New website enquiry</h2>
      <p style="margin:0 0 18px;color:#4B5B70">${esc(r.service)} in ${esc(r.postcode)}</p>
      <table style="border-collapse:collapse;font-size:15px">${rows}</table>
      <p style="margin-top:22px">
        <a href="tel:${esc(r.phone)}" style="background:#012F63;color:#fff;padding:10px 16px;border-radius:6px;text-decoration:none">Call ${esc(r.name)}</a>
      </p>
      <p style="color:#4B5B70;font-size:13px;margin-top:22px">Sent from swelectrical.co.uk. Also saved to the enquiry log.</p>
    </div>`;

  try {
    const res = await fetch('https://api.resend.com/emails', {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${env.RESEND_API_KEY}`,
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        from: env.FROM_EMAIL,
        to: [env.TO_EMAIL],
        reply_to: r.email,
        subject: `Website enquiry: ${r.service} (${r.postcode})`,
        html
      })
    });
    if (res.ok && env.DB) {
      await env.DB.prepare('UPDATE enquiries SET emailed = 1 WHERE id = ?').bind(r.id).run();
    }
  } catch {
    // Row stays with emailed = 0 so failures are visible in the log.
  }
}

async function listEnquiries(request, env) {
  if (!env.ADMIN_SECRET || request.headers.get('x-admin-secret') !== env.ADMIN_SECRET) {
    return json({ error: 'Unauthorised' }, 401);
  }
  if (!env.DB) return json({ error: 'Something went wrong at our end. Please call or WhatsApp Sean instead.' }, 500);

  const { results } = await env.DB.prepare(
    `SELECT id, created_at, name, phone, email, postcode, service, details,
            preferred, status, emailed
     FROM enquiries ORDER BY created_at DESC LIMIT 200`
  ).all();

  return json({ count: results.length, enquiries: results });
}

/* ------------------------------------------------------------------ */
/* EV charge point survey */

const SURVEY_PHOTO_SLOTS = ['consumer_unit', 'supply_meter', 'cable_route', 'charger_location'];
const SURVEY_MAX_PHOTO_BYTES = 8 * 1024 * 1024;   // matches the client-side compression ceiling
const SURVEY_MAX_PHOTOS_PER_SLOT = 6;
const SURVEY_MAX_VIDEO_BYTES = 60 * 1024 * 1024;  // raw — video isn't compressed client-side
const SURVEY_LINK_LIFETIME_SECONDS = 7 * 24 * 60 * 60; // 7 days
// field -> { max length, required?, message when missing, short name for "too long" }
const SURVEY_TEXT_FIELDS = {
  name:          { max: 100,  missing: 'Please enter your name.',                 short: 'name' },
  phone:         { max: 40,   missing: 'Please enter a phone number.',            short: 'phone number' },
  email:         { max: 200,  missing: 'Please enter an email address.',          short: 'email address' },
  postcode:      { max: 12,   missing: 'Please enter a postcode.',                short: 'postcode' },
  property_type: { max: 60,   missing: 'Please choose your property type.',       short: 'property type' },
  tenure:        { max: 20,                                                      short: 'answer' },
  parking_type:  { max: 60,   missing: 'Please choose where you park.',           short: 'parking answer' },
  charger_location_notes: { max: 1000,                                           short: 'charger location note' },
  ev_status:     { max: 40,                                                      short: 'answer' },
  preferred_time:{ max: 100,                                                     short: 'preferred time' },
  notes:         { max: 2000,                                                    short: 'note' }
};

async function handleEvSurvey(request, env, ctx) {
  const limited = await checkRateLimit(request, env, 'ev-survey');
  if (limited) return limited;

  let form;
  try {
    form = await request.formData();
  } catch {
    return json({ error: 'Your survey did not arrive complete, which usually means the connection dropped during the upload. Please try again on a stronger signal, or with fewer photos.' }, 400);
  }

  // Honeypot
  if (form.get('company')) return json({ ok: true }, 200);

  if (failsTimeTrap(form.get('form_started'))) return json({ ok: true }, 200);

  // Everything is validated before anything else happens, in this order:
  //   1. text fields   2. photos and video   3. Turnstile   4. uploads
  // Turnstile comes after validation because its tokens are single use (see
  // handleEnquiry). Files are all checked before any upload starts, so a bad
  // third photo can no longer leave the first two orphaned in storage.
  const clean = {};
  for (const [field, rule] of Object.entries(SURVEY_TEXT_FIELDS)) {
    const v = String(form.get(field) ?? '').trim();
    if (rule.missing && !v) return json({ error: rule.missing, field }, 400);
    if (v.length > rule.max) {
      return json({ error: `That ${rule.short} is too long. Please shorten it and try again.`, field }, 400);
    }
    clean[field] = v;
  }
  const bad = checkContact(clean);
  if (bad) return json(bad, 400);

  const filesBySlot = {};
  for (const slot of SURVEY_PHOTO_SLOTS) {
    const files = form.getAll('photo_' + slot)
      .filter((f) => typeof f !== 'string' && f.size > 0)
      .slice(0, SURVEY_MAX_PHOTOS_PER_SLOT);
    for (const file of files) {
      if (!file.type || !file.type.startsWith('image/')) {
        return json({ error: `One of the ${slotLabel(slot).toLowerCase()} photos is not an image file. Please remove it and add a photo instead.`, field: 'photo_' + slot }, 400);
      }
      if (file.size > SURVEY_MAX_PHOTO_BYTES) {
        return json({ error: `One of the ${slotLabel(slot).toLowerCase()} photos is too large. Please remove it and try a different photo.`, field: 'photo_' + slot }, 400);
      }
    }
    filesBySlot[slot] = files;
  }

  let videoFile = form.get('video_cable_route');
  if (!(videoFile && typeof videoFile !== 'string' && videoFile.size > 0)) videoFile = null;
  if (videoFile) {
    if (!videoFile.type || !videoFile.type.startsWith('video/')) {
      return json({ error: 'The cable route video is not a video file. Please remove it and add a video instead.', field: 'video_cable_route' }, 400);
    }
    if (videoFile.size > SURVEY_MAX_VIDEO_BYTES) {
      return json({ error: 'The cable route video is too large. Please record a shorter clip, around 20 seconds is plenty.', field: 'video_cable_route' }, 400);
    }
  }

  if (!(await verifyTurnstile(form.get('cf-turnstile-response'), env, request))) {
    return json({ error: 'The anti-spam check did not pass. Please tick the box again and resend.', turnstile: true }, 400);
  }

  if (!env.DB || !env.SURVEY_PHOTOS) {
    return json({ error: 'Something went wrong at our end. Please call or WhatsApp Sean instead.' }, 500);
  }

  const id = crypto.randomUUID();
  const photoKeysBySlot = {};   // slot -> array of R2 keys
  const mediaForEmail = [];     // { label, key, kind } — used to build view links
  const photoUploads = [];      // in-flight R2 writes

  // Files go to R2 as the File objects themselves rather than via
  // arrayBuffer(). The request body is already buffered by formData(), so
  // arrayBuffer() made a second full copy: with a near-limit phone video
  // that is well over 100MB against a 128MB Worker memory ceiling.
  for (const slot of SURVEY_PHOTO_SLOTS) {
    const keys = [];
    for (const file of filesBySlot[slot]) {
      const key = `ev-surveys/${id}/${slot}-${keys.length}.jpg`;
      keys.push(key);
      mediaForEmail.push({ label: slotLabel(slot) + ` (photo ${keys.length})`, key, kind: 'photo' });
      photoUploads.push(env.SURVEY_PHOTOS.put(key, file, { httpMetadata: { contentType: file.type } }));
    }
    if (keys.length) photoKeysBySlot[slot] = keys;
  }

  let videoKey = null;
  let videoUpload = null;
  if (videoFile) {
    videoKey = `ev-surveys/${id}/cable_route-video.mp4`;
    mediaForEmail.push({ label: 'Cable route (video)', key: videoKey, kind: 'video' });
    videoUpload = env.SURVEY_PHOTOS.put(videoKey, videoFile, { httpMetadata: { contentType: videoFile.type } });
  }

  try {
    await Promise.all(photoUploads);
  } catch {
    return json({ error: 'Your photos could not be saved at our end. Please try again, or send them to Sean on WhatsApp.' }, 500);
  }
  if (videoUpload) {
    try {
      await videoUpload;
    } catch {
      return json({ error: 'Your video could not be saved at our end. Please try again without it, or send it to Sean on WhatsApp.' }, 500);
    }
  }

  try {
    await env.DB.prepare(
      `INSERT INTO ev_surveys
         (id, name, phone, email, postcode, property_type, tenure, parking_type,
          charger_location_notes, ev_status, preferred_time, notes,
          photo_consumer_unit, photo_supply_meter, photo_cable_route, photo_charger_location,
          video_cable_route)
       VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`
    )
      .bind(
        id, clean.name, clean.phone, clean.email, clean.postcode,
        clean.property_type, clean.tenure || null, clean.parking_type,
        clean.charger_location_notes || null, clean.ev_status || null,
        clean.preferred_time || null, clean.notes || null,
        jsonOrNull(photoKeysBySlot.consumer_unit),
        jsonOrNull(photoKeysBySlot.supply_meter),
        jsonOrNull(photoKeysBySlot.cable_route),
        jsonOrNull(photoKeysBySlot.charger_location),
        videoKey
      )
      .run();
  } catch {
    return json({ error: 'Could not save survey' }, 500);
  }

  ctx.waitUntil(sendSurveyEmail(env, { id, ...clean, media: mediaForEmail }));

  return json({ ok: true }, 200);
}

function jsonOrNull(arr) {
  return arr && arr.length ? JSON.stringify(arr) : null;
}

function slotLabel(slot) {
  return {
    consumer_unit: 'Consumer unit',
    supply_meter: 'Supply and meter',
    cable_route: 'Cable route',
    charger_location: 'Charger location'
  }[slot] || slot;
}

/* ------------------------------------------------------------------ */
/* Signed view links for survey media.
   Photos and video are never emailed as attachments — video in particular
   would be far too large. Instead the notification email links to each
   file, and the link is only valid because it carries a signature only
   this worker could have produced (using ADMIN_SECRET as the signing key)
   and an expiry a week out. There is no separate secret to configure. */

async function hmacHex(secret, message) {
  const key = await crypto.subtle.importKey(
    'raw', new TextEncoder().encode(secret),
    { name: 'HMAC', hash: 'SHA-256' }, false, ['sign']
  );
  const sig = await crypto.subtle.sign('HMAC', key, new TextEncoder().encode(message));
  return Array.from(new Uint8Array(sig)).map((b) => b.toString(16).padStart(2, '0')).join('');
}

async function signMediaKey(key, env) {
  const exp = Math.floor(Date.now() / 1000) + SURVEY_LINK_LIFETIME_SECONDS;
  const sig = await hmacHex(env.ADMIN_SECRET, `${key}:${exp}`);
  const params = new URLSearchParams({ key, exp: String(exp), sig });
  return `/api/survey-media?${params.toString()}`;
}

async function serveSurveyMedia(request, env) {
  const url = new URL(request.url);
  const key = url.searchParams.get('key');
  const exp = url.searchParams.get('exp');
  const sig = url.searchParams.get('sig');

  if (!key || !exp || !sig || !env.ADMIN_SECRET) {
    return new Response('Not found', { status: 404 });
  }
  if (Date.now() / 1000 > Number(exp)) {
    return new Response('This link has expired', { status: 410 });
  }

  const expected = await hmacHex(env.ADMIN_SECRET, `${key}:${exp}`);
  if (expected !== sig) {
    return new Response('Not found', { status: 404 });
  }

  if (!env.SURVEY_PHOTOS) return new Response('Not found', { status: 404 });

  // Range support matters most for video: without it, a player can't ask
  // for just the bytes it needs next, so it either has to buffer the whole
  // file before playing (choppy start, no seeking) or stalls repeatedly.
  // head() gets the size and content-type without pulling the file body.
  const head = await env.SURVEY_PHOTOS.head(key);
  if (!head) return new Response('Not found', { status: 404 });

  const headers = new Headers();
  head.writeHttpMetadata(headers);
  headers.set('accept-ranges', 'bytes');
  headers.set('cache-control', 'private, max-age=3600');
  if (!headers.get('content-type')) headers.set('content-type', 'application/octet-stream');

  const rangeHeader = request.headers.get('range');
  const rangeMatch = rangeHeader && /^bytes=(\d*)-(\d*)$/.exec(rangeHeader);

  if (rangeMatch) {
    const size = head.size;
    let start = rangeMatch[1] ? parseInt(rangeMatch[1], 10) : undefined;
    let end = rangeMatch[2] ? parseInt(rangeMatch[2], 10) : undefined;

    if (start === undefined) {
      // Suffix range, e.g. "bytes=-500" means the last 500 bytes.
      start = Math.max(size - end, 0);
      end = size - 1;
    } else if (end === undefined || end >= size) {
      end = size - 1;
    }

    if (start > end || start >= size) {
      headers.set('content-range', `bytes */${size}`);
      return new Response(null, { status: 416, headers });
    }

    const object = await env.SURVEY_PHOTOS.get(key, { range: { offset: start, length: end - start + 1 } });
    if (!object) return new Response('Not found', { status: 404 });

    headers.set('content-range', `bytes ${start}-${end}/${size}`);
    headers.set('content-length', String(end - start + 1));
    return new Response(object.body, { status: 206, headers });
  }

  const object = await env.SURVEY_PHOTOS.get(key);
  if (!object) return new Response('Not found', { status: 404 });
  headers.set('content-length', String(head.size));
  return new Response(object.body, { status: 200, headers });
}

async function sendSurveyEmail(env, r) {
  if (!env.RESEND_API_KEY || !env.TO_EMAIL || !env.FROM_EMAIL) return;

  const esc = (s) =>
    String(s ?? '').replace(/[<>&]/g, (ch) => ({ '<': '&lt;', '>': '&gt;', '&': '&amp;' }[ch]));

  const rows = [
    ['Name', r.name], ['Phone', r.phone], ['Email', r.email], ['Postcode', r.postcode],
    ['Property type', r.property_type], ['Tenure', r.tenure],
    ['Parking', r.parking_type], ['Preferred charger location', r.charger_location_notes],
    ['EV status', r.ev_status], ['Best time to call', r.preferred_time], ['Notes', r.notes]
  ]
    .filter(([, v]) => v)
    .map(
      ([k, v]) =>
        `<tr><td style="padding:6px 14px 6px 0;vertical-align:top;color:#4B5B70">${esc(k)}</td>` +
        `<td style="padding:6px 0;vertical-align:top"><strong>${esc(v).replace(/\n/g, '<br>')}</strong></td></tr>`
    )
    .join('');

  let mediaHtml = '<p style="color:#4B5B70">No photos or video were attached to this survey.</p>';
  if (r.media.length) {
    const SITE_ORIGIN = 'https://swelectrical.co.uk';
    const links = await Promise.all(
      r.media.map(async (m) => {
        const path = await signMediaKey(m.key, env);
        const verb = m.kind === 'video' ? 'Watch' : 'View';
        return `<li style="margin-bottom:6px"><a href="${SITE_ORIGIN}${path}">${verb} — ${esc(m.label)}</a></li>`;
      })
    );
    mediaHtml =
      '<p style="color:#4B5B70;margin-bottom:6px">Photos and video (links open directly, valid for 7 days):</p>' +
      `<ul style="padding-left:1.1rem;margin:0">${links.join('')}</ul>`;
  }

  const html = `
    <div style="font-family:-apple-system,Segoe UI,sans-serif;color:#011E3E;max-width:600px">
      <h2 style="margin:0 0 4px">EV charge point survey</h2>
      <p style="margin:0 0 18px;color:#4B5B70">${esc(r.postcode)}</p>
      <table style="border-collapse:collapse;font-size:15px">${rows}</table>
      <div style="margin-top:16px">${mediaHtml}</div>
      <p style="margin-top:22px">
        <a href="tel:${esc(r.phone)}" style="background:#012F63;color:#fff;padding:10px 16px;border-radius:6px;text-decoration:none">Call ${esc(r.name)}</a>
      </p>
      <p style="color:#4B5B70;font-size:13px;margin-top:22px">Sent from the EV survey on swelectrical.co.uk. Also saved to the survey log.</p>
    </div>`;

  try {
    const res = await fetch('https://api.resend.com/emails', {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${env.RESEND_API_KEY}`,
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        from: env.FROM_EMAIL,
        to: [env.TO_EMAIL],
        reply_to: r.email,
        subject: `EV survey: ${r.name} (${r.postcode})`,
        html
      })
    });
    if (res.ok && env.DB) {
      await env.DB.prepare('UPDATE ev_surveys SET emailed = 1 WHERE id = ?').bind(r.id).run();
    }
  } catch {
    // Row stays with emailed = 0 so failures are visible in the log.
  }
}
